version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
    environment:
      - APP_ENV=local
    expose:
      - "9000"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../:/workspace:ro
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
